### PR TITLE
Add MarshalJSON for Result[T]

### PR DESCRIPTION
**Pull request by joel-u410**
I thought it would be useful to support JSON marshaling for `Result[T]`. This would likely be used within the context of building a JSON-RPC service, so I implemented it here in a way that generally conforms to the [JSON-RPC spec](https://www.jsonrpc.org/specification).

There is one notable exception, the spec requires a `code` field in an `error` object that indicates the type of error that occurred, and this information is not readily available from an `error` in Go. So I left that out, resulting in slight nonconformance to the spec.

I had thought about always including something like `code: -32000` as a general server error, but it seemed better to me to leave it out rather than inserting something that may or may not be correct in all situations.

If you think this is too opinionated a way to represent a `Result[T]` in JSON, feel free to reject & close this PR. 🙂

### CODE REVIEW

**Comment by samber** [comment]
Could you please add the unmarshaler?

**Comment by joel-u410** [comment]
Yep, will do!

**Comment by joel-u410** [comment]
The reason I hadn't originally implemented unmarshalling is because it's lossy going to JSON -- the error _type_ is lost (only the message is marshaled).

Are you ok with an unmarshal implementation that simply uses `errors.New` to construct a generic error object for the `Err` case?

**Review by samber — APPROVED** [review]

**Comment by samber** [comment]
Ok, I understand the limit of unmarshaling.

Using errors.New looks like a good workaround.

**Pull request merged**
